version: '3.7'

services:

  mysql: # Mysql container
    container_name: development-mysql
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      # - ./conf:/etc/mysql/conf.d
      # - ./logs:/var/log/mysql
      # - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: railstutorial
      MYSQL_USER:     test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 3306:3306

  pma: # phpMyAdmin container
    container_name: development-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: mysql
    ports:
      - 8080:80
    links:
      - mysql:db